# Generated by Django 5.1.3 on 2024-11-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='created_timestamp',
            new_name='creation_timestamp',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='expired_timestamp',
            new_name='expiration_timestamp',
        ),
    ]
